sudo: false

language: node_js
node_js:
- "6.9.4"

notifications:
    email: false

addons:
    apt:
        packages:
        - oracle-java8-set-default

install:
- npm install -g bower cordova ionic
- npm install
- bower update

before_script:
- wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
- tar -xvf android-sdk_r24.4-linux.tgz
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-24.0.0
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-24
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/24.0.0

script:
- export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
- npm install
- ionic platform remove android
- ionic platform add android
- ionic build android
